import type { Metadata, Viewport } from "next";

import { SERVER_CONFIG } from "@norish/config/env-config-server";
import { generateAppleWebAppSplashScreenConfigs } from "@norish/shared/lib/pwa/ios-startup-images";
import { siteConfig } from "@norish/web/config/site";

export const appMetadata: Metadata = {
  // Absolute base for resolving relative OG/Twitter image URLs (e.g. the
  // default share card). Falls back to undefined when the URL isn't set so a
  // build without AUTH_URL doesn't throw.
  metadataBase: SERVER_CONFIG.AUTH_URL ? new URL(SERVER_CONFIG.AUTH_URL) : undefined,
  title: {
    default: siteConfig.name,
    template: `%s | ${siteConfig.name}`,
  },
  description: siteConfig.description,
  // Default social-share card, so sharing the bare domain (or any page without
  // its own OG image) still shows a branded preview. Pages that build a richer
  // card — recipes, profiles, cookbooks — override this in their own metadata.
  openGraph: {
    type: "website",
    siteName: siteConfig.name,
    title: siteConfig.name,
    description: siteConfig.description,
    images: [{ url: "/og-default.png", width: 1200, height: 630, alt: siteConfig.name }],
  },
  twitter: {
    card: "summary_large_image",
    title: siteConfig.name,
    description: siteConfig.description,
    images: ["/og-default.png"],
  },
  manifest: "/manifest.webmanifest", // auto-generated by app/manifest.ts
  icons: {
    icon: [
      { url: "/favicon.svg", type: "image/svg+xml" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-96x96.png", sizes: "96x96", type: "image/png" },
      { url: "/android-chrome-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/android-chrome-512x512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
    shortcut: "/favicon.ico",
  },
  appleWebApp: {
    capable: true,
    title: siteConfig.name,
    statusBarStyle: "black-translucent",
    startupImage: generateAppleWebAppSplashScreenConfigs(),
  },
  other: {
    "apple-mobile-web-app-capable": "yes",
  },
  applicationName: siteConfig.name,
};

export const appViewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#336640" },
    { media: "(prefers-color-scheme: light)", color: "#fffef7" },
  ],
  interactiveWidget: "resizes-visual",
};
